name: Spearhead Theme Check

on:
  pull_request:
    paths:
    - spearhead/*'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2

        - name: Run Theme Check Action
          uses: StevenDufresne/wp-theme-validation-action-experiment@main
          id: theme-check
          with:
            accessible-ready: true
            root-folder: spearhead 
        
        - uses: actions/upload-artifact@v2
          if: ${{ always() }}
          with:
            name: Screenshots
            path: ${{ steps.theme-check.outputs.screenshots }}
